/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public\model\Character-Transformed.glb -T 
Files: public\model\Character-Transformed.glb [7.04MB] > D:\React-Three-Fiber-Webflow-master\React-Three-Fiber-Webflow-master\Character-Transformed-transformed.glb [1.66MB] (76%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Character(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./model/Character-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)
  console.log(names)


  useEffect(( ) => {
    actions[names[0]].reset().fadeIn(0.5).play();
  
  }, [] );
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[1.65, 0, 0]} position={[0, -2, 0]} scale={[2, 2, 2]}> 
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh castShadow receiveShadow name="10294136_0" geometry={nodes['10294136_0'].geometry} material={materials['Material.005']} skeleton={nodes['10294136_0'].skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Aviator_Glasses" geometry={nodes.Aviator_Glasses.geometry} material={materials['Material.007']} skeleton={nodes.Aviator_Glasses.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Socks} skeleton={nodes.Cylinder.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Socks} skeleton={nodes.Cylinder001.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials['Material.002']} skeleton={nodes.defaultMaterial.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Eyes" geometry={nodes.Eyes.geometry} material={materials['Eyes and Noes']} skeleton={nodes.Eyes.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Face" geometry={nodes.Face.geometry} material={materials.Skin} skeleton={nodes.Face.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Face001" geometry={nodes.Face001.geometry} material={materials.Mouth} skeleton={nodes.Face001.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Hoodie" geometry={nodes.Hoodie.geometry} material={materials['Material.001']} skeleton={nodes.Hoodie.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="image_(11)_(1)_(1)" geometry={nodes['image_(11)_(1)_(1)'].geometry} material={materials.Logo} skeleton={nodes['image_(11)_(1)_(1)'].skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="image_(11)_(1)_(1)001" geometry={nodes['image_(11)_(1)_(1)001'].geometry} material={materials.Logo} skeleton={nodes['image_(11)_(1)_(1)001'].skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="neck" geometry={nodes.neck.geometry} material={materials.Skin} skeleton={nodes.neck.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Nose" geometry={nodes.Nose.geometry} material={materials['Eyes and Noes']} skeleton={nodes.Nose.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Skin} skeleton={nodes.Object_17.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Object_17001" geometry={nodes.Object_17001.geometry} material={materials.Skin} skeleton={nodes.Object_17001.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Sneeker} skeleton={nodes.Plane001.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Plane076" geometry={nodes.Plane076.geometry} material={materials.Sneeker} skeleton={nodes.Plane076.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Sharp_Cuban_Link_Chain002" geometry={nodes.Sharp_Cuban_Link_Chain002.geometry} material={materials['Gold Chain']} skeleton={nodes.Sharp_Cuban_Link_Chain002.skeleton} rotation={[1.65, 0, 0]} />
        <skinnedMesh castShadow receiveShadow name="Shirt" geometry={nodes.Shirt.geometry} material={materials.Material_10} skeleton={nodes.Shirt.skeleton} rotation={[1.65, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('./model/Character-transformed.glb')
